# This is a basic workflow to help you get started with Actions

name: Import Project

on:
  workflow_dispatch: # Manual trigger
    inputs:
      project:
        description: "The project to download and publish"
        required: true
      distributionName:
        description: "The name of the distribution directory"
        required: true
  
  repository_dispatch: # Trigger via webhook
    types: [Import Project]


jobs:
  import:
    name: 📥 Import maven release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
        
      - name: Download built maven repo
        uses: dawidd6/action-download-artifact@v3
        with:
          repo: cph101/${{ github.event.inputs.project || github.event.client_payload.project }}
          name: maven-repo
          workflow: publish.yml 
          path: ./releases/${{ github.event.inputs.distributionName || github.event.client_payload.distributionName }}
          
      - name: Rename maven repo
        run: |
          cd ./releases/
          mv ${{ github.event.inputs.distributionName || github.event.client_payload.distributionName }}/maven-metadata-local.xml ${{ github.event.inputs.distributionName || github.event.client_payload.distributionName }}/maven-metadata.xml

      - name: Commit Built Repo
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add --all
          git commit -m "Uploaded new version of ${{ github.event.inputs.distributionName || github.event.client_payload.distributionName }}"
          git push origin main
